# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
