# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='message_text',
        ),
    ]
